### PR TITLE
Added new authors to CWP

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
@eduardo-rodrigues - I think you need to start a new branch for these changes from `master` or to rebase. There seem to be far too many commits here that have already been applied into `master`. As most of the PRs are resolved using a rebase commits do change their hash, even if not their content.

**Comment by eduardo-rodrigues** [comment]
Damn, you're right. I was only looking at the diff, which is the one line I want to add. Thanks.

**Comment by eduardo-rodrigues** [comment]
Dummy question since I'm not a "rebase" user (at least so far): can I use the butting above "rebase and merge" instead of "squash and merge"? Or do I need to do the rebase in my fork, locally? Thanks.

**Comment by graeme-a-stewart** [comment]
You need to rebase locally - the problem is that all the original commits conflict with the rebased ones on the master branch as they touch the same lines.

In fact, for this MR, probably the easiest way to do it is to create a new clean feature branch from master, then just cherry-pick the only needed commit off this muddled-up branch with

`git cherry-pick 4e2f6e29d41bbbbf0976bc1085f3634469771b05`

This should give you a feature branch with a single commit difference with master that can be merged cleanly.

**Comment by eduardo-rodrigues** [comment]
OK, then let me close this dirty MR.

**Comment by eduardo-rodrigues** [comment]
Hmm, tried fresh and still see a few commits. Maybe because of my fork, the fact of getting it in sync with the "upstream", which is the HSF repo. I have to read a bit as I'm not used to rebase. Thanks again.

**Pull request closed without merging**
